apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-anime
  labels:
    app: crawler-anime
spec:
  replicas: 5
  selector:
    matchLabels: 
      app: crawler-anime
  template:
    metadata:
      labels:
        app: crawler-anime
    spec:
      containers:
        - name: crawler-anime
          image: gcr.io/anime-rec-dev/crawler_image
          env:
            - name: SCHEDULER_DB
              valueFrom:
                secretKeyRef:
                  name: scheduler-db-credentials
                  key: dbname
            - name: SCHEDULER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: scheduler-db-credentials
                  key: user
            - name: SCHEDULER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scheduler-db-credentials
                  key: password
            - name: PROJECT_ID
              value: anime-rec-dev
            - name: SCHEDULE_ANIME_PUBSUB_SUBSCRIPTION
              value: anime_crawl_subscription
            - name: SCHEDULE_PROFILE_PUBSUB_SUBSCRIPTION
              value: profile_crawl_subscription
            - name: DATA_INGESTION_PUBSUB_TOPIC
              value: data_ingestion_queue
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/scheduler_db_instance_credentials.json
          command: ["python3"] 
          args: ["anime_crawl_worker.py"]
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
              readOnly: true
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.23.0
          command : ["/cloud_sql_proxy",
                     "-instances=anime-rec-dev:us-central1:scheduler-db-instance-dev-small=tcp:5432",
                     "-credential_file=/secrets/scheduler_db_instance_credentials.json"]
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: scheduler-db-instance-credentials
