apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-profile-no-db
  labels:
    app: crawler-profile-no-db
spec:
  replicas: 30
  selector:
    matchLabels: 
      app: crawler-profile-no-db
  template:
    metadata:
      labels:
        app: crawler-profile-no-db
    spec:
      containers:
        - name: crawler-profile
          image: gcr.io/anime-rec-dev/crawler_image:latest
          env:
            - name: PROJECT_ID
              value: anime-rec-dev
            - name: SCHEDULE_ANIME_PUBSUB_SUBSCRIPTION
              value: anime_crawl_subscription
            - name: SCHEDULE_PROFILE_PUBSUB_SUBSCRIPTION
              value: profile_crawl_subscription
            - name: DATA_INGESTION_PUBSUB_TOPIC
              value: data_ingestion_queue
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gcp_credentials.json
          command: ["python3"] 
          args: ["crawl_worker.py", "--profile", "--crawled_output", "pubsub", "--jikan", "--max_urls", "100"]
          volumeMounts:
            - name: secrets-volume
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: secrets-volume
          secret:
            secretName: gcp-credentials
